### ISSUE TITLE
I set up a MOAC Chinese pool and need MOAC project Pangu 0.8.1 test to mine.

### ISSUE THREAD

**Issue by dacelee** [MOACChain/moac-core#10]
I set up a MOAC Chinese pool and need MOAC project Pangu 0.8.1（Linux）  test to mine.
After the official version of MOAC is released, I can build a long-term Chinese node.
Please provide a MOAC 0.8.1 download, thank you.

http://moac.in/

**Comment by mdranger** [comment]
You can find the 0.8.1 release from github release tab.
https://github.com/MOACChain/moac-core/releases/download/0.8.1/MOAC-Pangu0.8.1-Ubuntu.tar.gz

**Comment by mdranger** [comment]
We also have a mining pool already setup by a third party
http://moacpool.tk/

**Comment by dacelee** [comment]
It's been built, thank you.
Can you add http://moac.in/ to URL navigation?

**Comment by mdranger** [comment]
Thanks for your interest in using MOAC. Feel free to work on the projects as long as you follow our license agreement.

**Comment by dacelee** [comment]
Please provide a MOAC 0.8.2 download, thank you.
How many blocks will start mainnet？

**Comment by mdranger** [comment]
Please go to our release page to find the download packages
https://github.com/MOACChain/moac-core/releases
