### ISSUE TITLE
Looks the test net of Pangu081 has been paused for more than 1 hour.

### ISSUE THREAD

**Issue by foreso-GitHub** [MOACChain/moac-core#11]
Looks the test net of Pangu081 has been paused for more than 1 hour.
And no new block has been generated since 1 hour ago.

![image](https://user-images.githubusercontent.com/31951179/39127387-71a4c462-4737-11e8-8b85-e07e1639501f.png)

**Comment by mdranger** [comment]
The delay of the block generation was caused by the decrease of computing power in the system. MOAC block difficulty changed with the computing power in the system. The difficulty of the block decreased 5% between block 69215 and block 69216, indicating some computing power left the mining pool.
