### ISSUE TITLE
In Ubuntu, cannot connect to Moac node after it start for 20 minutes.

### ISSUE THREAD

**Issue by foreso-GitHub** [MOACChain/moac-core#12]
Hi guys, I met a problem in Ubuntu system.  When I start my local moac node (by cmd: sudo ./moac --testnet --rpc --rpcapi="chain3,mc,net,personal,admin,debug,miner,txpool,db" --rpccorsdomain="*"), in the first about 20 minutes, I can connect the node by HttpProvider("http://localhost:8545") in program.  But after 20 minutes, I cannot connect the node anymore.  Only after restart the Ubuntu system, I can connect the node in program for about 20 minutes again.  But at the same time, I can connect the moac node by console by cmd: ./moac attach http://localhost:8545.  So it looks the moac node is okay.

I guess there are 2 possible reasons:
1. There is some setting wrong or limit in my Ubuntu, but I did find any clue.
Or 
2. This is a bug in Chain3.

Here is my nodejs code:

var chain3 = new Chain3(new Chain3.providers.HttpProvider("http://localhost:8545"));
var mc = chain3.mc;
var amountSha = mc.getBalance(address);

This code works well in the first 20 minutes when the moac node starts.  After 20 minutes, error through as following:

 ::ffff:180.169.225.186 POST /v1/balance Error: CONNECTION ERROR: Couldn't connect to node http://localhost:8545.
    at Object.InvalidConnection (/usr/local/moac-end/node_modules/chain3/lib/chain3/errors.js:34:16)
    at HttpProvider.send (/usr/local/moac-end/node_modules/chain3/lib/chain3/httpprovider.js:99:18)
    at RequestManager.send (/usr/local/moac-end/node_modules/chain3/lib/chain3/requestmanager.js:53:32)
    at Mc.send [as getBalance] (/usr/local/moac-end/node_modules/chain3/lib/chain3/method.js:148:58)
    at Object.getBalance (/usr/local/moac-end/modules/moac/moacOperation.js:59:28)
    at /usr/local/moac-end/modules/moac/moacRouter.js:70:40
    at Layer.handle [as handle_request] (/usr/local/moac-end/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/local/moac-end/node_modules/express/lib/router/route.js:137:13)
    at /usr/local/moac-end/node_modules/body-parser/lib/read.js:130:5
    at invokeCallback (/usr/local/moac-end/node_modules/raw-body/index.js:224:16)

I tried to change the localhost to 127.0.0.1 but it did not work.  

This problem doesn't happen in Windows system.

**Comment by foreso-GitHub** [comment]
Ubuntu version: Ubuntu 16.04.3 LTS \n \l

**Comment by foreso-GitHub** [comment]
Moac version: Pangu 0.8.1

**Comment by foreso-GitHub** [comment]
But the same problem exists when I used Pangu 0.8.0.

**Comment by biajee** [comment]
The attach code looks like this:
`./moac attach ipc:/path-to-your-ipc/moac.ipc`

**Comment by mdranger** [comment]
We can not repeat the problem of Chain3 as you described. We used it to run the explorer all the time. Can you check your ubuntu settings? Are you using a cloud machine?

**Comment by foreso-GitHub** [comment]
Yes you are right.  After I delopy the moac node and program in a new ubuntu server, this problem doesn't happen again.  Both ubuntu servers are on Ali cloud, FYI.  Thank you!
