### ISSUE TITLE
Please provide a MOAC 0.8.2 Linux download, thank you. How many blocks will start mainnet？

### ISSUE THREAD

**Issue by dacelee** [MOACChain/moac-core#13]
Please provide a MOAC 0.8.2 Linux download or windows , thank you.
How many blocks will start mainnet？

**Comment by mdranger** [comment]
Please check our release page for the download links.
https://github.com/MOACChain/moac-core/releases
Thanks.

**Comment by mdranger** [comment]
We just released Mac OS package

**Comment by mdranger** [comment]
https://github.com/MOACChain/moac-core/releases/download/0.8.2/pangu0.8.2MacOS.tar.gz
