### ISSUE TITLE
"chain3.transaction is not a constructor" is pop up when transfer in Moac.

### ISSUE THREAD

**Issue by foreso-GitHub** [MOACChain/moac-core#15]
When I make a transaction, the error is pop up "chain3.transaction is not a constructor", when this line is executed:
var tx = new chain3.transaction(rawTx);

The chain3 version is 0.1.4.  

Did you change the interface of chain3?  Is there interface description of the new version of chain3?

**Comment by mdranger** [comment]
Yes, version0.1.4 removed the  transaction object and used signTransaction. New example is under example/send_mc.
You can build the rawTx in JSON format and sign it with the account private key.
    var rawTx = {
      from: src.addr,
      nonce: chain3.intToHex(txcount),
      gasPrice: chain3.intToHex(2000000000),
      gasLimit: chain3.intToHex(5000000),
      to: '0xf1f5b7a35dff6400af7ab3ea54e4e637059ef909',
      value: chain3.intToHex(chain3.toSha(value, 'mc')), 
      data: '0x00',
      chainId: chainid
    }

    var cmd1 = chain3.signTransaction(rawTx, src["key"]);

**Comment by foreso-GitHub** [comment]
Thank you, it works.
