### ISSUE TITLE
How pangu0.8 testnet opens SCS mining？

### ISSUE THREAD

**Issue by dacelee** [MOACChain/moac-core#16]
Do you have any related documents?

**Comment by biajee** [comment]
SCS function is not released, yet. Therefore, we cannot do SCS mining at the moment. SCS mining will be available as soon as the SCS function is released.

**Comment by dacelee** [comment]
Node synchronization failure in China
I have set up two long-term block nodes for MOAC for China.
hangzhou
enode://946b4b0565bdd0a7ac811203b0a76beed10a6cbc3b161123b9db57809d6b3799946f33f114e3225d9cc78634254492e20921f6d897cb6cf6cbd6e31a886930c4@47.96.152.29:30333
shanghai
enode://8b424bbb41d834308fcddb0d02ccbd8747ddcc36dceaad49da8a2123f637f8331884bb4fd2ae133a9bdc23fec79f511fe9200a053f8e3567720f134b4b3b7eaa@47.100.242.127:30333

**Comment by mdranger** [comment]
We released the SCS client on Jun 30th, 2018. Please check the release Pangu0.8.4.
