### ISSUE TITLE
Is there any method of chain3 that I can get the transaction list of an address?

### ISSUE THREAD

**Issue by foreso-GitHub** [MOACChain/moac-core#17]
Is there any method of chain3 that I can get the transaction list of an address?

Now I can only get one transaction by transaction hash, by using chain3.mc.getTransactionReceipt(hash).

**Comment by mdranger** [comment]
Chain3 is only a RPC interface connecting with the MOAC node. Like Ethereum node, the MOAC node itself saved the TXs by blocks, not by address. Usually you need to have a local database storing all the transactions and related them with address, like 
http://explorer.moac.io/addr/0x030379ea919fe0bd0f4e4de5cecb24e0b7333611.

**Comment by foreso-GitHub** [comment]
I see, thanks.  So I need do it by myself, or wait someone to develop such a third-part function, right?

**Comment by foreso-GitHub** [comment]
Got it, thank you!
