### ISSUE TITLE
取得块信息mc.block(3150)报错

### ISSUE THREAD

**Issue by xudong7930** [MOACChain/moac-core#18]
在moac的console里面调用:  chain3.mc.block(3150) 报错,根本显示块信息:
TypeError: 'block' is not a function
    at <anonymous>:1:1

反倒是mc.getBlock(3150)可以,  copy过来也不好好改改

**Comment by heipacker** [comment]
@xudong7930 
chain3.mc.getBlock('3150')
用这个吧

**Comment by caivega** [comment]
@xudong7930 can you query the block info by web3.eth.block(...) ? 
`
> web3.eth.block(510000)
TypeError: 'block' is not a function
    at <anonymous>:1:1
`

**Comment by mdranger** [comment]
The document was updated and the correct command is:
> chain3.mc.getBlock('3150')
