### ISSUE TITLE
When I npm install chain3, error occurs.

### ISSUE THREAD

**Issue by foreso-GitHub** [MOACChain/moac-core#19]
As following.  This error did not occur in chain3 0.1.4.  Is it a problem of 0.1.6?

[#26#spc-moac-end]$sudo npm install chain3
npm ERR! code 1
npm ERR! Command failed: /usr/bin/git clone -q https://github.com/frozeman/bignumber.js-nolookahead.git /home/skywell/.npm/_cacache/tmp/git-clone-ae11ddb4
npm ERR! /home/skywell/.npm/_cacache/tmp/git-clone-ae11ddb4/.git: Permission denied
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/skywell/.npm/_logs/2018-05-15T04_46_05_896Z-debug.log
[#27#spc-moac-end]$sudo npm install chain3
npm ERR! code 1
npm ERR! Command failed: /usr/bin/git clone -q https://github.com/frozeman/bignumber.js-nolookahead.git /home/skywell/.npm/_cacache/tmp/git-clone-a357a484
npm ERR! /home/skywell/.npm/_cacache/tmp/git-clone-a357a484/.git: Permission denied
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/skywell/.npm/_logs/2018-05-15T04_46_26_380Z-debug.log

**Comment by caivega** [comment]
it seems that your network broken or you don't have the permission to write the dir /home/skywell/.npm/_cacache/tmp/

**Comment by foreso-GitHub** [comment]
It works now, and I have updated to 0.1.6.  Thanks Weijia!
