### ISSUE TITLE
v0.1.1 release file format for ubuntu

### ISSUE THREAD

**Issue by lospringliu** [MOACChain/moac-core#2]
when the file is unzipped, the file format is windows instead of unix

**Comment by heipacker** [comment]
?

**Comment by lospringliu** [comment]
For text file, it is normally different when save under *nix and win* platforms

- on win* platforms, EOL (end of line) is CR + LF (carriage return + line feed)
- on *nix platforms, EOL is simply CR

In this case, under ubuntu, inexperienced user can not run it actually, they will hit such error

```shell
ubuntu@ib21b08:/tmp/ubuntu$ file initmoac.sh 
initmoac.sh: POSIX shell script, ASCII text executable, with CRLF line terminators
ubuntu@ib21b08:/tmp/ubuntu$ bash initmoac.sh 
initmoac.sh: line 2: $'\r': command not found
initmoac.sh: line 4: ./moac: Permission denied
initmoac.sh: line 5: $'\r': command not found
initmoac.sh: line 6: ./scsserver: Permission denied
```

**Comment by lospringliu** [comment]
there are utilities like **dos2unix** and **unix2dos** to make the format transform

you can also solve this in your git repository with **.gitattributes** configuration

**Comment by mdranger** [comment]
Thanks for your interest. New version Pangu0.8 is released for testing.
