### ISSUE TITLE
Is there any way I can get the transactions in queued queue?

### ISSUE THREAD

**Issue by foreso-GitHub** [MOACChain/moac-core#23]
Sometimes there are some transactions cannot be pending (maybe because wrong nonce) and stay in queued for long time.  But I don't know which transactions are in queued.  

Is there any way (console or chain3) I can get the transactions in queued?  So I can execute new transaction with right nonce to make all the transactions work.

**Comment by mdranger** [comment]
You need to keep the TX HASH as reference to check the TX status. Then you can check the TX status by using chain3.mc.getTransaction.
You can find the latest nonce by using chain3.mc.getTransactionCount. Then you can replace the TX with higher gasPrice.
If you can attach to a MOAC node with the console, you can check the txpool status under the console:
txpool.status
and txpool.inspect to check which TXs are currently pending

**Comment by foreso-GitHub** [comment]
I know txpool.status, but I did not know txpool.inspect.  It is helpful, thanks!  

Where I can see all the help of command line, include txpool command?  These 2 links are too simple.
https://github.com/MOACChain/moac-core/wiki/Console
https://github.com/MOACChain/moac-core/wiki/Commands

**Comment by mdranger** [comment]
You are right. We should put more info there. For Chain3, you can find more info in the github repos:
https://github.com/innowells/Chain3/blob/master/Chain3.md
MOAC project was forked from Ethereum and modified to create more capabilities, such as sharding and subchain. You can check Ethereum documents if you can't find them here.
We will put more stuff here soon. Thanks.

**Comment by foreso-GitHub** [comment]
Thanks!
