### ISSUE TITLE
How can I get the result of executing method of smart contract?

### ISSUE THREAD

**Issue by foreso-GitHub** [MOACChain/moac-core#26]
In eth, I can get the smart contract method result by the status item in transactionReceipt, as following.
{
        "blockHash": "0x6a277aa325decb2fe1ff2171179539d3221d55152078c281a399b19736286512",
        "blockNumber": 3387026,
        "contractAddress": null,
        "cumulativeGasUsed": 36931,
        "from": "0x09104882f8a1269b0e3e64d47aa180636823ec1a",
        "gasUsed": 36931,
        "logs": [
            {
                "address": "0x807498FB105f0F05fc9854f98128500DE684C048",
                "topics": [
                    "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef",
                    "0x00000000000000000000000009104882f8a1269b0e3e64d47aa180636823ec1a",
                    "0x000000000000000000000000dbc02f7819d8f88dd473974ca516afc78700d3bf"
                ],
                "data": "0x00000000000000000000000000000000000000000000000564d702d38f5e0000",
                "blockNumber": 3387026,
                "transactionHash": "0xeac083bcbed408797a7a33d834d39ed47be3fdf912c286a5bc1ce473a531332c",
                "transactionIndex": 0,
                "blockHash": "0x6a277aa325decb2fe1ff2171179539d3221d55152078c281a399b19736286512",
                "logIndex": 0,
                "removed": false,
                "id": "log_3e086e47"
            }
        ],
        "logsBloom": "0x00000000000000008000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008000000000000000000000000400000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000040000000000000000400000000000000000000000000000000000000000000000000000000000000000000000000000120000000000002000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000004000",
        "status": true,
        "to": "0x807498fb105f0f05fc9854f98128500de684c048",
        "transactionHash": "0xeac083bcbed408797a7a33d834d39ed47be3fdf912c286a5bc1ce473a531332c",
        "transactionIndex": 0
    }
}

But in moac, there is no status item in transactionReceipt as following, how can I know the result?
{
        "blockHash": "0x7f9336a29fe99178eb1463a95fac8961c08c49b8dc4a0165af05831a9d98aee1",
        "blockNumber": 261536,
        "contractAddress": "0x3de4c3b9add4f95c74adeb538537f68b7c6dccb4",
        "cumulativeGasUsed": 16953,
        "from": "0x460420a40a694e2efbc5defdb8a0a76f3134ecfb",
        "gasUsed": 16953,
        "logs": [
            {
                "address": "0x3de4c3b9add4f95c74adeb538537f68b7c6dccb4",
                "topics": [
                    "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef",
                    "0x000000000000000000000000460420a40a694e2efbc5defdb8a0a76f3134ecfb",
                    "0x000000000000000000000000dbc02f7819d8f88dd473974ca516afc78700d3bf"
                ],
                "TxData": "0x00000000000000000000000000000000000000000000000564d702d38f5e0000",
                "blockNumber": 261536,
                "transactionHash": "0xc03a1e431e41bde4b8b954b34dbb1ec5aea17c33c39e67e97b05de67b34b3f06",
                "transactionIndex": 1,
                "blockHash": "0x7f9336a29fe99178eb1463a95fac8961c08c49b8dc4a0165af05831a9d98aee1",
                "logIndex": 0,
                "removed": false
            }
        ],
        "logsBloom": "0x00000000000000000000000001000000000000000000000000000000020000000000020000000000000000000000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000210000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000000000002000000000000000000000020000000000000000000000000000000000000000000000000000000100000000000001000000000000000000000000000",
        "root": "0x",
        "to": "0x3de4c3b9add4f95c74adeb538537f68b7c6dccb4",
        "transactionHash": "0xc03a1e431e41bde4b8b954b34dbb1ec5aea17c33c39e67e97b05de67b34b3f06",
        "transactionIndex": 1
    }
}

Btw, I found there is logs.id and status in eth receipt, but not in moac's.  But moac receipt has root item, which doesn't exist in eth receipt.
 What's the usage of logs.id and root in eth and moac?

**Comment by mdranger** [comment]
MOAC was developed based on a earlier version of GETH. The receipt status was introduced in GETH after METROPOLIS_FORK. We have added this feature in 0.8.3 and will release it with the subchain feature. If you want to test it, please leave your email and the OS. We can send you a compiled version for testing.

**Comment by foreso-GitHub** [comment]
Yes I want to do it.  foreso@sina.com, thanks!
