### ISSUE TITLE
Transaction is always in pending

### ISSUE THREAD

**Issue by foreso-GitHub** [MOACChain/moac-core#28]
We send a transaction which with input data this morning but it is always in pending till now (for 1 hour now).

Why isn't it executed and always in pending?

Here is the hash of the transaction.
0x34a1adce30f2d54586d06dd7a5af584e5d1e0863146edc759f241f87b9e24e3d

**Comment by mdranger** [comment]
If the gas price is not high enough, it may stay in the pending pool for a long time. This is because no miners want to take low gas price transaction. You can try to replace the TX with higher gas price. Or start mining on the local node.

**Comment by foreso-GitHub** [comment]
No, not this reason, we used high price as following.

"gasLimit":40000,"gasPrice":"25000000000"

**Comment by foreso-GitHub** [comment]
Now there are 27 transaction in pending in testnet.  Looks the testnet doesn't sync for more than 1 hour.  Please have a look, thanks!

**Comment by foreso-GitHub** [comment]
It is 12:55 2018-6-14 in Beijing time.

**Comment by foreso-GitHub** [comment]
It looks because the node doesn't sync for long time.  In our 4 nodes, the last block is 309775.  It has not been updated for more than 1.5 hours still now.  So the transactions are always in pending.  It is a problem often happens in testnet.  Even from the testnet explorer, the last block is 309692 and has not been updated for more than 2 hours.

It is hard to work on testnet sometimes because this problem.  **If we want to attract and help more developers to work on MOAC, please try to improve the performance of testnet.**  Thanks!

**Comment by foreso-GitHub** [comment]
![explorer](https://user-images.githubusercontent.com/31951179/41447809-d553a64c-7089-11e8-84e2-44c1b7594c93.png)

**Comment by mdranger** [comment]
Thanks for your information. It seems the miner got some problem synching with the network. We are working to fix it.

**Comment by mdranger** [comment]
We have added a new miner to the testnet. Now all the TXs went through.

**Comment by foreso-GitHub** [comment]
Thanks mdranger!  Will let you know if this problem happen again.

**Comment by foreso-GitHub** [comment]
Looks the testnet is frozen again.  Now the last block number is 342364.  And the testnet explorer (http://47.75.144.55:3000/home) is down, too.
