### ISSUE TITLE
The scs cannot generate subchain block.

### ISSUE THREAD

**Issue by foreso-GitHub** [MOACChain/moac-core#32]
I tried to create sub chain in moac testnet.  Following the guide in wiki (https://github.com/MOACChain/moac-core/wiki/%E5%AD%90%E9%93%BE), I accomplished following steps.
1. deploy vnodeprotocolbase.sol.
2. register vnode proxy.
3. deploy subchainprotocolbase.sol.
4. register 2 scs in pool.
5. deploy subchainbase.sol.
6. registerOpen.
7. registerClose.

As the guide says, after registerClose, the scs should init the subchain and start to generate subchain blocks automatically.  But it never happened.

All these steps get TRUE in status (in transactions).  And I checked, the 2 scs had already in the nodeList of subchainbase.  

Does anyone have any idea or suggestion for it?  Thanks!

**Comment by mdranger** [comment]
Please use the most recent pangu0.8.4 package and try using 3 SCSs in the pool. For the existing subchainbase.sol, it requires 2/3 vote in the MicroChain to generate blocks. If you only have 2 and they didn't agree with each other at first, it may get confused. 
If you still get the problem, please attach SCS logs and we can check it.

**Comment by foreso-GitHub** [comment]
Thanks mdranger.  After I download pangu0.8.4 again, I found it is a little different from the 0.8.4 I used.  And it works now.  

But how can I know the newest version released?  They are both pangu0.8.4 and no version update, and no tips/notification in the release page about update.

**Comment by mdranger** [comment]
Hi, Foreso, please note that Pangu0.8.4 is still a pre-release package. We are still developing it and may update it without notice. 
If you have any problem with existing package, please come back and check your package with the most recent one, or leave us your questions here.
For a future stable release, we will notify the community in advance if any changes have been made.

**Comment by foreso-GitHub** [comment]
I see, thanks!
