### ISSUE TITLE
The moac file is not correct in nuwa1.0.1.win.zip

### ISSUE THREAD

**Issue by foreso-GitHub** [MOACChain/moac-core#38]
The moac file is not a windows exe file in the nuwa1.0.1.win.zip.  Looks it is an Ubuntu version of moac.

![nuwa101](https://user-images.githubusercontent.com/31951179/43572567-77a2151a-9672-11e8-934b-b65da6078bdd.png)

BTW, in Chinese Pinyin, 女娲 should be "nvwa", not "nuwa".  "nuwa" sounds like 牛蛙 in Pinyin.  :-P

**Comment by mdranger** [comment]
Just fixed and put a new file in the release.
Thanks.
