### ISSUE TITLE
restart error

### ISSUE THREAD

**Issue by heipacker** [MOACChain/moac-core#4]
INFO [04-10|02:03:20.793] 6:[vnode/scsservices.go->VnodeServiceStart]
WARN [04-10|02:03:20.793] No moacbase set and no accounts found as default
INFO [04-10|02:03:20.794] 1:Starting peer-to-peer node             instance=Moac/v0.8.0-develop-64ebf697/linux-amd64/go1.10
INFO [04-10|02:03:20.794] Allocated cache and file handles         database=/root/.moac/testnet/moac/chaindata cache=128 handles=1024
gc 2 @0.049s 0%: 0.004+1.1+0.047 ms clock, 0.039+0.20/0.64/1.0+0.38 ms cpu, 37->37->35 MB, 38 MB goal, 8 P
gc 3 @0.052s 1%: 0.007+1.1+0.054 ms clock, 0.061+0/1.0/1.7+0.43 ms cpu, 67->67->35 MB, 71 MB goal, 8 P
INFO [04-10|02:03:20.807] 1:Disk storage enabled for ethash caches dir=/root/.moac/testnet/moac/ethash count=3
INFO [04-10|02:03:20.808] 1:Disk storage enabled for ethash DAGs   dir=/root/.ethash                   count=2
INFO [04-10|02:03:20.808] 1:Initializing MoacNode protocol         versions="[63 62]" network=3
INFO [04-10|02:03:20.809] 1:Loaded most recent local header        number=75689 hash=0x67c61b0396bea070b197f0f470a41e2ebe75922aa4d55d53ef4467b1df0ecd9f td=36163962224608
INFO [04-10|02:03:20.809] 1:Loaded most recent local full block    number=75689 hash=0x67c61b0396bea070b197f0f470a41e2ebe75922aa4d55d53ef4467b1df0ecd9f td=36163962224608
INFO [04-10|02:03:20.809] 1:Loaded most recent local fast block    number=75689 hash=0x67c61b0396bea070b197f0f470a41e2ebe75922aa4d55d53ef4467b1df0ecd9f td=36163962224608
INFO [04-10|02:03:20.809] 1:[core/tx_pool.go->TxPool.AddLocal]
INFO [04-10|02:03:20.810] 1:validateTx                             cost:=1002494800000000000
WARN [04-10|02:03:20.810] Failed to journal local transaction      err="no active journal"
INFO [04-10|02:03:20.810] 1:txpool.promoteExecutable               addr nonce=15
INFO [04-10|02:03:20.810] 1:txlist.checkready                      cur txlist=&[15]
INFO [04-10|02:03:20.811] 1:Promoting queued transaction           hash=0x34995ba534feaac29821ab78c75924b9fd4aeb2087b8c444123e5a301bd57cfa
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x68 pc=0x99f844]

goroutine 1 [running]:
github.com/innowells/MoacCore/networkrelay.(*NetworkRelay).GetNewRequestId(...)
        /home/ubuntu/MoacCore/build/_workspace/src/github.com/innowells/MoacCore/networkrelay/network_relay.go:116
github.com/innowells/MoacCore/core.(*TxPool).promoteTx(0xc4246e3340, 0x9ba44c2cacf214d8, 0xba7ee9e482650633, 0xa55b9934b92a2fe0, 0x78ab2198c2aafe34, 0x20eb4afdb92459c7, 0x305a3e1244c4b887, 0xfa7cd51b, 0xc4200f4840)
        /home/ubuntu/MoacCore/build/_workspace/src/github.com/innowells/MoacCore/core/tx_pool.go:764 +0x7e4
github.com/innowells/MoacCore/core.(*TxPool).promoteExecutables(0xc4246e3340, 0xc4205861f4, 0x1, 0x1)
        /home/ubuntu/MoacCore/build/_workspace/src/github.com/innowells/MoacCore/core/tx_pool.go:1008 +0x832
github.com/innowells/MoacCore/core.(*TxPool).addTx(0xc4246e3340, 0xc4200f4840, 0x1, 0x0, 0x0)
        /home/ubuntu/MoacCore/build/_workspace/src/github.com/innowells/MoacCore/core/tx_pool.go:873 +0x19b
github.com/innowells/MoacCore/core.(*TxPool).AddLocal(0xc4246e3340, 0xc4200f4840, 0x1, 0xc4200f4840)
        /home/ubuntu/MoacCore/build/_workspace/src/github.com/innowells/MoacCore/core/tx_pool.go:832 +0x69
github.com/innowells/MoacCore/core.(*TxPool).AddLocal-fm(0xc4200f4840, 0xf70f20, 0xc4200f4840)
        /home/ubuntu/MoacCore/build/_workspace/src/github.com/innowells/MoacCore/core/tx_pool.go:240 +0x34
github.com/innowells/MoacCore/core.(*txJournal).load(0xc4202cdf00, 0xc420586458, 0x0, 0x0)
        /home/ubuntu/MoacCore/build/_workspace/src/github.com/innowells/MoacCore/core/tx_journal.go:78 +0x182
github.com/innowells/MoacCore/core.NewTxPool(0x0, 0xc420388600, 0x29, 0x34630b8a000, 0x1, 0xa, 0x10, 0xa000, 0x40, 0x400, ...)
        /home/ubuntu/MoacCore/build/_workspace/src/github.com/innowells/MoacCore/core/tx_pool.go:240 +0x5d7
github.com/innowells/MoacCore/mc.New(0xc42036a0c0, 0xc420179500, 0xf42720, 0xc42058b7e8, 0x4171a8)
        /home/ubuntu/MoacCore/build/_workspace/src/github.com/innowells/MoacCore/mc/backend.go:173 +0x835
github.com/innowells/MoacCore/cmd/utils.RegisterMoacService.func2(0xc42036a0c0, 0xc4205a18c0, 0xc42058baf0, 0x2, 0x2)
        /home/ubuntu/MoacCore/build/_workspace/src/github.com/innowells/MoacCore/cmd/utils/flags.go:1026 +0x3d
github.com/innowells/MoacCore/node.(*Node).Start(0xc42010e6c0, 0x0, 0x0)
        /home/ubuntu/MoacCore/build/_workspace/src/github.com/innowells/MoacCore/node/node.go:178 +0x3c2
github.com/innowells/MoacCore/cmd/utils.StartNode(0xc42010e6c0)
        /home/ubuntu/MoacCore/build/_workspace/src/github.com/innowells/MoacCore/cmd/utils/cmd.go:62 +0x2f
main.startNode(0xc420110160, 0xc42010e6c0)
        /home/ubuntu/MoacCore/build/_workspace/src/github.com/innowells/MoacCore/cmd/moac/main.go:265 +0x43
main.moac(0xc420110160, 0x100a178, 0xb2d05e00)
        /home/ubuntu/MoacCore/build/_workspace/src/github.com/innowells/MoacCore/cmd/moac/main.go:223 +0x69
github.com/innowells/MoacCore/vendor/gopkg.in/urfave/cli%2ev1.HandleAction(0xdea8e0, 0x100ba58, 0xc420110160, 0xc420110160, 0xc42058bf10)
        /home/ubuntu/MoacCore/build/_workspace/src/github.com/innowells/MoacCore/vendor/gopkg.in/urfave/cli.v1/app.go:492 +0xc8
github.com/innowells/MoacCore/vendor/gopkg.in/urfave/cli%2ev1.(*App).Run(0xc4200d84e0, 0xc4200ca000, 0x9, 0x9, 0x0, 0x0)
        /home/ubuntu/MoacCore/build/_workspace/src/github.com/innowells/MoacCore/vendor/gopkg.in/urfave/cli.v1/app.go:266 +0x5ee
main.main()
        /home/ubuntu/MoacCore/build/_workspace/src/github.com/innowells/MoacCore/cmd/moac/main.go:207 +0x148
gc 1 @0.034s 0%: 0.023+0.93+0.077 ms clock, 0.18+0/1.1/1.1+0.62 ms cpu, 4->4->3 MB, 5 MB goal, 8 P

**Comment by biajee** [comment]
Thank you for finding this bug. One of the value was not initialized.
