### ISSUE TITLE
B6、Check MicroChain status

### ISSUE THREAD

**Issue by abc114437** [MOACChain/moac-core#40]
![20180806133928](https://user-images.githubusercontent.com/22112598/43702159-6214942c-998b-11e8-9ef3-09898f7babf1.png)
How to define common.Address?
Do you have an example of a complete call?
If there is any, please give me help.
Thanks!

**Comment by foreso-GitHub** [comment]
Hi, as I know, common.Address is defined in package "github.com/ethereum/go-ethereum/common".  You just need import this package.

Here is my go sample for microchain, for your information.

**Comment by foreso-GitHub** [comment]
package main
import (
	"fmt"
	"net/rpc"
	"github.com/ethereum/go-ethereum/common"
	"math/big"
	)

type Args struct {
    Sender       common.Address      // Dapp创建者
    SubChainAddr common.Address
}

type ArgsData struct {
    Sender       common.Address     // Dapp创建者
    SubChainAddr common.Address
    Func         string                            // eg:"SetData()", "rpcGetData()"
}

type ContractInfoReq struct {
    Reqtype      int//查询类型0: 查看合约全部变量 , 1: 查看合约某一个数组变量 , 2: 查看合约某一个mapping变量 , 3: 查看合约某一个结构体变量, 4: 查看合约某一简单类型变量（单倍长度存储的变量）, 5: 查看合约某一变长变量（如string、bytes）
    Key          string//64位定长十六进制字符串，查询的变量在合约里面的index ，查询全部变量时可以不填
    Position     string//64位定长十六进制字符串，当Reqtype==1时，Position为数组里第几个变量（从0开始）；当Reqtype==2时，Position为mapping下标
    Structformat []byte//当出现结构体变量时，此变量描述结构，结构体只允许出现1-single（简单类型变量单倍长度存储的变量）, 2-list（简单类型数组变量）, 3-string变长变量（如string、bytes），若结构变量为ContractInfoReq，Structformat = []byte{‘1’,’3’,’3’,’3’}
}

type GetContractInfoReq struct {
    SubChainAddr common.Address//合约地址
    Request      []ContractInfoReq//查询合约全部变量数据，数据太大，可以选择查询需要的几个变量
}

type ContractInfo struct {
    Balance  *big.Int
    Nonce    uint64
    Root     common.Hash
    CodeHash []byte
    Code     []byte
    Storage  map[string]string
}


func main() {
serverAddress := "localhost"

serverPort := "9545"

sender := common.HexToAddress("0x924b82ae920d343b176c3a47d7d3b881471fe76a")  
subchain := common.HexToAddress("0x25a2d3e1ac426e441c106615b9ef1711d20a1c06")  
args := Args{Sender: sender, SubChainAddr: subchain}  
client, err := rpc.DialHTTP("tcp", serverAddress+":"+serverPort)
fmt.Println("err:", err, client) 
var scsid common.Address
client.Call("ScsRPCMethod.GetScsId", args, &scsid)
fmt.Println("")
fmt.Println("scsid:", scsid)

var nonce uint64
client.Call("ScsRPCMethod.GetNonce", args, &nonce)
fmt.Println("")
fmt.Println("nonce:", nonce)

var replyData []byte
argsData := ArgsData{sender, subchain, "getValue()"}
client.Call("ScsRPCMethod.GetData", argsData, &replyData)
fmt.Println("")
fmt.Println("getValue:", replyData)

var reply uint64
client.Call("ScsRPCMethod.GetDappState", args, &reply)
fmt.Println("")
fmt.Println("GetDappState:", reply)

var conInfo ContractInfo
conReq := ContractInfoReq{0, "0", "0", []byte{'1','3','3','3'}}
conReqList := []ContractInfoReq{conReq}
getConReq := GetContractInfoReq{subchain, conReqList}
client.Call("ScsRPCMethod.GetContractInfo", getConReq, &conInfo)
fmt.Println("")
fmt.Println("GetContractInfo:", conInfo)
}
