### ISSUE TITLE
Did Nuwa SCS and FileStorm release?

### ISSUE THREAD

**Issue by foreso-GitHub** [MOACChain/moac-core#41]
@mdranger Did we release Nuwa SCS and FileStorm on 8/8 as the plan?  Just checked the release page but did not find any new updates.

**Comment by mdranger** [comment]
Not yet, we need to check if most of the mining powers are upgraded. It will be released soon.

**Comment by foreso-GitHub** [comment]
Got it, thanks!

**Comment by mdranger** [comment]
Nuwa SCS and VNODE were released in verison 1.0.2. FileStorm will be released next week.
