### ISSUE TITLE
Can't get more than 2 peers.

### ISSUE THREAD

**Issue by Serpent6877** [MOACChain/moac-core#43]
MOAC nuwa 1.0.2-stable (Tried 1.0.1) as well.

I can not seem to establish more than 2 peers after running for 48 hours.

curl -X POST --data '{"jsonrpc":"2.0","method":"net_peerCount","params":[],"id":101}' localhost:18011
{"jsonrpc":"2.0","id":101,"result":"0x2"}

moac --fast --cache=2048 --rpc --rpcaddr 127.0.0.1 --rpcport 18011 --nat extip:X.X.X.X --port 38011 --maxpeers 75 --unlock 0x711635d6c48d9301e865548851605ddca2b9ca9e --password passfile

Any recommendations?

**Comment by Serpent6877** [comment]
Trimmed down the command line to see if it was port or some other issue:

moac --fast --cache=2048 --rpc --rpcaddr 127.0.0.1 --rpcport 18011 --unlock 0x711635d6c48d9301e865548851605ddca2b9ca9e --password passfile

Still seems to be the same issue. I immediately get 2 peers but no others connect. This is on a fast dedicated server with a 1Gb connection in a datacenter. 

curl -X POST --data '{"jsonrpc":"2.0","method":"net_peerCount","params":[],"id":101}' localhost:18011
{"jsonrpc":"2.0","id":101,"result":"0x2"}

**Comment by dacelee** [comment]
-rpcaddr 127.0.0.1 --rpcport 8545 --nat extip：XXXX --port 30333

**Comment by Serpent6877** [comment]
Well the default port is 30333 so the above would of worked.

**Comment by mdranger** [comment]
You can see the peers you connected with:
`> admin.peers`

Then you should see some info like this:

> caps: ["mc/62", "mc/63"],
>     id: "f9ef2e39d2083a21b58e8f9ccae61910e7a6d82f49ea0b72b83f5e5fc7f11ff8f280937f480793cc8ff7ac8c814ec2b56922e88d2094b796e5624bf8cb1cb472",
>     name: "Moac/v1.0.1-stable-e014a747/linux-amd64/go1.9.4",
>     network: {
>       localAddress: "172.31.27.255:30333",
>       remoteAddress: "47.100.52.2:54296"

Please let us know which servers are you connected with so we can help you further.
We have servers in North America, Europe and Asia.
You can also try to connect with testnet and see if you have better connections.

**Comment by Serpent6877** [comment]
I have now moved to just one peer:

`instance: Moac/moac.digipools.org/v1.0.2-stable-632a21f0/linux-amd64/go1.10
coinbase: 0x711635d6c48d9301e865548851605ddca2b9ca9e
at block: 691485 (Tue, 14 Aug 2018 09:59:32 PDT)
 datadir: /opt/moacpool/.moac
 modules: admin:1.0 chain3:1.0 debug:1.0 mc:1.0 miner:1.0 net:1.0 personal:1.0 rpc:1.0 txpool:1.0 vnode:1.0

> admin.peers
[{
    caps: ["mc/62", "mc/63"],
    id: "3d8ba7cef2dcc8e25bd508e6a42d7b36a957afe8dc5cd9603ffd0857aae68b2768a06de6054816edec407a4579b15b5c7494e9c7e8323b015d6e9d518576e9eb",
    name: "Moac/v1.0.0-stable-5546a085/windows-amd64/go1.10.1",
    network: {
      localAddress: "45.43.30.2:51924",
      remoteAddress: "18.233.50.84:30333"
    },
    protocols: {
      mc: {
        difficulty: 13072040613449091000,
        head: "0x07e549abc59b2935109e18c75e1d4e5e9bc92789a4316921b80869fd451b7d3c",
        version: 63
      }
    }
}]
`

I run many other pools and have no issues with peers. I removed the nodes files but did not remove the nodekey. Still no luck.

**Comment by mdranger** [comment]
We used AWS to provide the node service. It seems you are connected with one of them in USA. You can try some others:
	"enode://6f29307c8715502c11791704759d88910e091f5d4a6daf509fc9d0d8653967fd2cda76c94731e2db6654ff889a684a55f9a6bc6f0b3144282eb2c3e7cbccb4b1@18.211.187.153:30333",
	"enode://1cf0eb6052ee692e85cf5447c9b1ef95c57f23e2efe1cd8cd5a01b44feadc3395f3aa02e0b1130dffcfdac3225b3ce8d773bfd148efadc3846353337a45c99a2@54.71.244.228:30333",
	"enode://bebab9587e939fab7e21922864cdf6668193e1fcfe5f69ef128216c96e5e08dae1a8d9b99e0cb158bd040c9ac249c3569d43675f0e637fb2cf9e2df9e39738d7@52.34.175.72:30333",
	"enode://624c26083a9be2ac0624bc5e4d88633aca89f62bbca1e7929a05bfc9f06a42202168b12ed5303f95e26296f8092d07b61071eedaccfe7027ceb0e7330589bc5c@13.211.142.153:30333",
	//Canada central
	"enode://4c8fac5ed1f8e5676d8f6b722fdb69b289dd58fe5844f0ae036b9d257bc6c4ebb94641cd590f8d7ed282c7690217eaf17898712b974ce23cfccbe167edc1faa0@35.182.237.1:30333"

**Comment by Serpent6877** [comment]
Here is something interesting. Here is my command line:

moac --cache=2048 --rpc --rpcaddr 127.0.0.1 --rpcport 18011 --nat extip:45.43.30.5 --port 38011 --unlock 0x711635d6c48d9301e865548851605ddca2b9ca9e --password pass --bootnodes enode://6f29307c8715502c11791704759d88910e091f5d4a6daf509fc9d0d8653967fd2cda76c94731e2db6654ff889a684a55f9a6bc6f0b3144282eb2c3e7cbccb4b1@18.211.187.153:30333,enode://3d8ba7cef2dcc8e25bd508e6a42d7b36a957afe8dc5cd9603ffd0857aae68b2768a06de6054816edec407a4579b15b5c7494e9c7e8323b015d6e9d518576e9eb@18.233.50.84:30333,enode://1cf0eb6052ee692e85cf5447c9b1ef95c57f23e2efe1cd8cd5a01b44feadc3395f3aa02e0b1130dffcfdac3225b3ce8d773bfd148efadc3846353337a45c99a2@54.71.244.228:30333 --verbosity 5

It will only connect to the first two nodes in the list no matter what order I set. I can connect to each of these individually. But anymore than two and they never connect.

`TRACE[08-15|00:36:46.034] Starting bonding ping/pong               id=1cf0eb6052ee692e known=false failcount=0 age=426199h36m46.034824281s
TRACE[08-15|00:36:46.034] Starting bonding ping/pong               id=6f29307c8715502c known=false failcount=0 age=426199h36m46.034892583s
TRACE[08-15|00:36:46.034] Starting bonding ping/pong               id=3d8ba7cef2dcc8e2 known=false failcount=0 age=426199h36m46.034877635s
DEBUG[08-15|00:36:46.035] 119:[rlp/encode.go->makeWriter] reflect.Struct 
DEBUG[08-15|00:36:46.035] 119:[rlp/encode.go->makeWriter] reflect.Struct 
DEBUG[08-15|00:36:46.035] 119:[rlp/encode.go->makeWriter] reflect.Ptr 
TRACE[08-15|00:36:46.036] >> PING/v4                               addr=54.71.244.228:30333 err=nil
TRACE[08-15|00:36:46.036] >> PING/v4                               addr=18.233.50.84:30333  err=nil
TRACE[08-15|00:36:46.036] >> PING/v4                               addr=18.211.187.153:30333 err=nil
DEBUG[08-15|00:36:46.535] 116:No discv4 seed nodes found 
TRACE[08-15|00:36:46.535] Dial task done                           task="discovery lookup"
TRACE[08-15|00:36:46.535] New dial task                            task="discovery lookup"
INFO [08-15|00:36:47.778] 1:Unlocked account address=0x711635D6C48d9301E865548851605DDca2B9CA9E 
INFO [08-15|00:36:47.778] 60:[rpc/inproc.go->DialInProc] 
TRACE[08-15|00:36:50.020] Starting bonding ping/pong               id=1cf0eb6052ee692e known=false failcount=0 age=426199h36m50.020830293s
TRACE[08-15|00:36:50.020] Starting bonding ping/pong               id=3d8ba7cef2dcc8e2 known=false failcount=0 age=426199h36m50.020940416s
TRACE[08-15|00:36:50.020] Starting bonding ping/pong               id=6f29307c8715502c known=false failcount=0 age=426199h36m50.020937242s
TRACE[08-15|00:36:50.021] >> PING/v4                               addr=54.71.244.228:30333  err=nil
TRACE[08-15|00:36:50.021] >> PING/v4                               addr=18.233.50.84:30333   err=nil
TRACE[08-15|00:36:50.021] >> PING/v4                               addr=18.211.187.153:30333 err=nil
DEBUG[08-15|00:36:50.521] 120:No discv4 seed nodes found 
TRACE[08-15|00:36:50.521] Dial task done                           task="discovery lookup"
TRACE[08-15|00:36:50.521] New dial task                            task="discovery lookup"
TRACE[08-15|00:36:54.021] Starting bonding ping/pong               id=1cf0eb6052ee692e known=false failcount=0 age=426199h36m54.021789832s
TRACE[08-15|00:36:54.021] Starting bonding ping/pong               id=6f29307c8715502c known=false failcount=0 age=426199h36m54.021884667s
TRACE[08-15|00:36:54.021] Starting bonding ping/pong               id=3d8ba7cef2dcc8e2 known=false failcount=0 age=426199h36m54.021835483s
TRACE[08-15|00:36:54.022] >> PING/v4                               addr=54.71.244.228:30333  err=nil
TRACE[08-15|00:36:54.022] >> PING/v4                               addr=18.211.187.153:30333 err=nil
TRACE[08-15|00:36:54.022] >> PING/v4                               addr=18.233.50.84:30333   err=nil
DEBUG[08-15|00:36:54.522] 132:No discv4 seed nodes found 
TRACE[08-15|00:36:54.522] Dial task done                           task="discovery lookup"
TRACE[08-15|00:36:54.522] New dial task                            task="discovery lookup"
TRACE[08-15|00:36:58.023] Starting bonding ping/pong               id=1cf0eb6052ee692e known=false failcount=0 age=426199h36m58.023637611s
TRACE[08-15|00:36:58.023] Starting bonding ping/pong               id=3d8ba7cef2dcc8e2 known=false failcount=0 age=426199h36m58.023803838s
TRACE[08-15|00:36:58.023] Starting bonding ping/pong               id=6f29307c8715502c known=false failcount=0 age=426199h36m58.023693009s
TRACE[08-15|00:36:58.024] >> PING/v4                               addr=54.71.244.228:30333  err=nil
TRACE[08-15|00:36:58.024] >> PING/v4                               addr=18.233.50.84:30333   err=nil
TRACE[08-15|00:36:58.024] >> PING/v4                               addr=18.211.187.153:30333 err=nil
DEBUG[08-15|00:36:58.524] 64:No discv4 seed nodes found 
TRACE[08-15|00:36:58.524] Dial task done                           task="discovery lookup"
TRACE[08-15|00:36:58.524] New dial task                            task="discovery lookup"
TRACE[08-15|00:37:02.022] Starting bonding ping/pong               id=1cf0eb6052ee692e known=false failcount=0 age=426199h37m2.022566437s
TRACE[08-15|00:37:02.022] Starting bonding ping/pong               id=6f29307c8715502c known=false failcount=0 age=426199h37m2.022769165s
TRACE[08-15|00:37:02.022] Starting bonding ping/pong               id=3d8ba7cef2dcc8e2 known=false failcount=0 age=426199h37m2.022770039s
TRACE[08-15|00:37:02.023] >> PING/v4                               addr=54.71.244.228:30333  err=nil
TRACE[08-15|00:37:02.023] >> PING/v4                               addr=18.211.187.153:30333 err=nil
TRACE[08-15|00:37:02.023] >> PING/v4                               addr=18.233.50.84:30333   err=nil
DEBUG[08-15|00:37:02.523] 276:No discv4 seed nodes found 
TRACE[08-15|00:37:02.523] Dial task done                           task="discovery lookup"
TRACE[08-15|00:37:02.523] New dial task                            task="discovery lookup"
TRACE[08-15|00:37:06.023] Starting bonding ping/pong               id=1cf0eb6052ee692e known=false failcount=0 age=426199h37m6.023092012s
TRACE[08-15|00:37:06.023] Starting bonding ping/pong               id=3d8ba7cef2dcc8e2 known=false failcount=0 age=426199h37m6.02317908s
TRACE[08-15|00:37:06.023] Starting bonding ping/pong               id=6f29307c8715502c known=false failcount=0 age=426199h37m6.023187243s
TRACE[08-15|00:37:06.023] >> PING/v4                               addr=54.71.244.228:30333  err=nil
TRACE[08-15|00:37:06.023] >> PING/v4                               addr=18.233.50.84:30333   err=nil
TRACE[08-15|00:37:06.023] >> PING/v4                               addr=18.211.187.153:30333 err=nil
DEBUG[08-15|00:37:06.523] 126:No discv4 seed nodes found 
TRACE[08-15|00:37:06.523] Dial task done                           task="discovery lookup"
TRACE[08-15|00:37:06.523] New dial task                            task="dyndial 6f29307c8715502c 18.211.187.153:30333"
TRACE[08-15|00:37:06.524] New dial task                            task="discovery lookup"
DEBUG[08-15|00:37:06.589] 197:[rlp/encode.go->makeWriter] reflect.Array 
DEBUG[08-15|00:37:06.589] 197:[rlp/encode.go->makeWriter] reflect.Array 
DEBUG[08-15|00:37:06.590] 197:[rlp/encode.go->makeWriter] reflect.Array 
DEBUG[08-15|00:37:06.590] 197:[rlp/encode.go->makeWriter] reflect.Struct 
DEBUG[08-15|00:37:06.590] 197:[rlp/encode.go->makeWriter] reflect.Ptr 
DEBUG[08-15|00:37:06.658] 197:[rlp/encode.go->makeWriter] reflect.Struct 
TRACE[08-15|00:37:06.659] New dial task                            task="dyndial 3d8ba7cef2dcc8e2 18.233.50.84:30333"
DEBUG[08-15|00:37:06.659] 280:[rlp/encode.go->makeWriter] reflect.Struct 
DEBUG[08-15|00:37:06.660] 280:[rlp/encode.go->makeWriter] kind == reflect.Slice || kind == reflect.Array 
DEBUG[08-15|00:37:06.660] 280:[rlp/encode.go->makeWriter] reflect.Struct 
DEBUG[08-15|00:37:06.660] 280:[rlp/encode.go->makeWriter] reflect.Ptr 
DEBUG[08-15|00:37:06.660] 46:Adding p2p peer id=6f29307c8715502c11791704759d88910e091f5d4a6daf509fc9d0d8653967fd2cda76c94731e2db6654ff889a684a55f9a6bc6f0b3144282eb2c3e7cbccb4b1 name=Moac/v1.0.0-stable-5... addr=18.211.187.153:30333 peers=1 
TRACE[08-15|00:37:06.660] Dial task done                           task="dyndial 6f29307c8715502c 18.211.187.153:30333"
TRACE[08-15|00:37:06.660] Starting protocol mc/63                  id=6f29307c8715502c conn=dyndial
DEBUG[08-15|00:37:06.660] MoacNode Peer connected                  id=6f29307c8715502c conn=dyndial name=Moac/v1.0.0-stable-5546a085/linux-amd64/go1.10.1
DEBUG[08-15|00:37:06.661] 284:[rlp/encode.go->makeWriter] isUint(kind) 
DEBUG[08-15|00:37:06.661] 284:[rlp/encode.go->makeWriter] reflect.Struct 
DEBUG[08-15|00:37:06.661] 284:[rlp/encode.go->makeWriter] reflect.Ptr 
TRACE[08-15|00:37:06.724] Registering sync peer                    peer=6f29307c8715502c
DEBUG[08-15|00:37:06.725] 283:[mc/handler.go->pm.handleMsg] 
DEBUG[08-15|00:37:06.725] 283:no chain available 
DEBUG[08-15|00:37:06.726] 283:[mc/handler.go->pm.handleMsg] 
DEBUG[08-15|00:37:06.803] 46:Adding p2p peer id=3d8ba7cef2dcc8e25bd508e6a42d7b36a957afe8dc5cd9603ffd0857aae68b2768a06de6054816edec407a4579b15b5c7494e9c7e8323b015d6e9d518576e9eb name=Moac/v1.0.0-stable-5... addr=18.233.50.84:30333 peers=2 
TRACE[08-15|00:37:06.803] Dial task done                           task="dyndial 3d8ba7cef2dcc8e2 18.233.50.84:30333"
TRACE[08-15|00:37:06.803] Starting protocol mc/63                  id=3d8ba7cef2dcc8e2 conn=dyndial
DEBUG[08-15|00:37:06.803] MoacNode Peer connected                  id=3d8ba7cef2dcc8e2 conn=dyndial name=Moac/v1.0.0-stable-5546a085/windows-amd64/go1.10.1
TRACE[08-15|00:37:06.871] Registering sync peer                    peer=3d8ba7cef2dcc8e2
DEBUG[08-15|00:37:06.871] 288:Relaxed downloader QoS values        rtt=20s confidence=0.500 ttl=1m0s
DEBUG[08-15|00:37:06.871] 288:[mc/handler.go->pm.handleMsg] 
DEBUG[08-15|00:37:06.871] 288:no chain available 
DEBUG[08-15|00:37:06.872] 288:[mc/handler.go->pm.handleMsg] 
TRACE[08-15|00:37:10.022] Starting bonding ping/pong               id=6f29307c8715502c known=false failcount=0 age=426199h37m10.022469253s
TRACE[08-15|00:37:10.022] Starting bonding ping/pong               id=1cf0eb6052ee692e known=false failcount=0 age=426199h37m10.022467522s
TRACE[08-15|00:37:10.022] Starting bonding ping/pong               id=3d8ba7cef2dcc8e2 known=false failcount=0 age=426199h37m10.022489211s
TRACE[08-15|00:37:10.022] >> PING/v4                               addr=18.211.187.153:30333 err=nil
TRACE[08-15|00:37:10.023] >> PING/v4                               addr=54.71.244.228:30333  err=nil
TRACE[08-15|00:37:10.023] >> PING/v4                               addr=18.233.50.84:30333   err=nil
DEBUG[08-15|00:37:10.299] 283:[rlp/encode.go->makeWriter] typ.Implements(encoderInterface) 
DEBUG[08-15|00:37:10.299] 283:[rlp/encode.go->makeWriter] reflect.Struct 
DEBUG[08-15|00:37:10.299] 283:[rlp/encode.go->makeWriter] reflect.Struct 
DEBUG[08-15|00:37:10.300] 283:[mc/handler.go->pm.handleMsg] 
DEBUG[08-15|00:37:10.300] 178:Queued propagated block              peer=6f29307c8715502c number=695359 hash=0x87930ca3a81cfc2de1ac376d198c6f1a2652931118d61d12626ff5ee12395b06 queued=1
DEBUG[08-15|00:37:10.323] 288:[mc/handler.go->pm.handleMsg] 
DEBUG[08-15|00:37:10.522] 307:No discv4 seed nodes found 
TRACE[08-15|00:37:10.523] Dial task done                           task="discovery lookup"
TRACE[08-15|00:37:10.523] New dial task                            task="discovery lookup"
TRACE[08-15|00:37:14.022] Starting bonding ping/pong               id=1cf0eb6052ee692e known=false failcount=0 age=426199h37m14.022685688s
TRACE[08-15|00:37:14.022] Starting bonding ping/pong               id=3d8ba7cef2dcc8e2 known=false failcount=0 age=426199h37m14.022755727s
TRACE[08-15|00:37:14.022] Starting bonding ping/pong               id=6f29307c8715502c known=false failcount=0 age=426199h37m14.022709722s
TRACE[08-15|00:37:14.023] >> PING/v4                               addr=54.71.244.228:30333  err=nil
TRACE[08-15|00:37:14.023] >> PING/v4                               addr=18.233.50.84:30333   err=nil
TRACE[08-15|00:37:14.023] >> PING/v4                               addr=18.211.187.153:30333 err=nil
DEBUG[08-15|00:37:14.523] 202:No discv4 seed nodes found 
TRACE[08-15|00:37:14.523] Dial task done                           task="discovery lookup"
TRACE[08-15|00:37:14.523] New dial task                            task="discovery lookup"
INFO [08-15|00:37:16.017] 206:Block synchronisation started 
DEBUG[08-15|00:37:16.017] 206:Synchronising with the network       peer=6f29307c8715502c mc=63 head=0x67372c2f9ba1a1fe50303bca76baf1cabd9e5c26f88efa18a0c3b1746bdc82d9 td=13179791045687922546 mode=full
DEBUG[08-15|00:37:16.017] Retrieving remote chain height           peer=6f29307c8715502c
DEBUG[08-15|00:37:16.017] Fetching batch of headers                id=6f29307c8715502c conn=dyndial count=1 fromhash=0x67372c2f9ba1a1fe50303bca76baf1cabd9e5c26f88efa18a0c3b1746bdc82d9 skip=0 reverse=false
DEBUG[08-15|00:37:16.017] 207:[rlp/encode.go->makeWriter] reflect.PtrTo(typ).Implements(encoderInterface) 
DEBUG[08-15|00:37:16.017] 207:[rlp/encode.go->makeWriter] reflect.Bool 
DEBUG[08-15|00:37:16.017] 207:[rlp/encode.go->makeWriter] reflect.Struct 
DEBUG[08-15|00:37:16.017] 207:[rlp/encode.go->makeWriter] reflect.Ptr 
TRACE[08-15|00:37:16.082] Filtering headers                        headers=1
DEBUG[08-15|00:37:16.082] 283:[mc/handler.go->pm.handleMsg] 
DEBUG[08-15|00:37:16.082] Remote head header identified            peer=6f29307c8715502c number=695358 hash=0x67372c2f9ba1a1fe50303bca76baf1cabd9e5c26f88efa18a0c3b1746bdc82d9
DEBUG[08-15|00:37:16.082] Looking for common ancestor              peer=6f29307c8715502c local=695357 remote=695358
DEBUG[08-15|00:37:16.082] Fetching batch of headers                id=6f29307c8715502c conn=dyndial count=13 fromnum=695165 skip=15 reverse=false
DEBUG[08-15|00:37:16.147] 283:[mc/handler.go->pm.handleMsg] 
DEBUG[08-15|00:37:16.147] Found common ancestor                    peer=6f29307c8715502c number=695357 hash=0x056af2305cd664ab67d05c1c41db403acd5a6903192edbbec8503c9bcfa95df7
DEBUG[08-15|00:37:16.148] Directing header downloads               peer=6f29307c8715502c origin=695358
TRACE[08-15|00:37:16.148] Fetching skeleton headers                peer=6f29307c8715502c count=192 from=695358
DEBUG[08-15|00:37:16.148] Fetching batch of headers                id=6f29307c8715502c conn=dyndial count=128 fromnum=695549 skip=191 reverse=false
DEBUG[08-15|00:37:16.148] 143:Downloading transaction receipts     origin=695358
DEBUG[08-15|00:37:16.148] 142:Downloading block bodies             origin=695358
DEBUG[08-15|00:37:16.212] 283:[mc/handler.go->pm.handleMsg] 
TRACE[08-15|00:37:16.212] Fetching full headers                    peer=6f29307c8715502c count=192 from=695358
DEBUG[08-15|00:37:16.212] Fetching batch of headers                id=6f29307c8715502c conn=dyndial count=192 fromnum=695358 skip=0   reverse=false
DEBUG[08-15|00:37:16.276] 283:[mc/handler.go->pm.handleMsg] 
TRACE[08-15|00:37:16.277] Scheduling new headers                   peer=6f29307c8715502c count=2   from=695358
TRACE[08-15|00:37:16.277] Fetching full headers                    peer=6f29307c8715502c count=192 from=695360
DEBUG[08-15|00:37:16.277] Fetching batch of headers                id=6f29307c8715502c conn=dyndial count=192 fromnum=695360 skip=0   reverse=false
TRACE[08-15|00:37:16.277] Requesting new batch of data             peer=6f29307c8715502c type=bodies count=2   from=695358
DEBUG[08-15|00:37:16.277] Fetching batch of block bodies           id=6f29307c8715502c conn=dyndial count=2
DEBUG[08-15|00:37:16.277] 323:[rlp/encode.go->makeWriter] kind == reflect.Slice || kind == reflect.Array 
DEBUG[08-15|00:37:16.341] 283:[mc/handler.go->pm.handleMsg] 
DEBUG[08-15|00:37:16.341] No more headers available                peer=6f29307c8715502c
DEBUG[08-15|00:37:16.341] Header download terminated               peer=6f29307c8715502c
DEBUG[08-15|00:37:16.341] 143:Data fetching completed              type=receipts
DEBUG[08-15|00:37:16.341] 143:Transaction receipt download terminated err=nil
DEBUG[08-15|00:37:16.341] 283:[rlp/encode.go->makeWriter] reflect.Struct 
DEBUG[08-15|00:37:16.341] 283:[rlp/encode.go->makeWriter] reflect.Ptr 
DEBUG[08-15|00:37:16.342] 283:[rlp/encode.go->makeWriter] kind == reflect.Slice || kind == reflect.Array 
TRACE[08-15|00:37:16.342] Filtering bodies                         txs=2 uncles=2
DEBUG[08-15|00:37:16.342] 283:[mc/handler.go->pm.handleMsg] 
TRACE[08-15|00:37:16.342] Peer throughput measurements updated     peer=6f29307c8715502c hps=0.000 bps=3.074 rps=0.000 sps=0.000 miss=0 rtt=18.00650705s
TRACE[08-15|00:37:16.342] Delivered new batch of data              peer=6f29307c8715502c type=bodies   count=2:2
DEBUG[08-15|00:37:16.342] 145:Inserting downloaded chain           items=2 firstnum=695358 firsthash=0x67372c2f9ba1a1fe50303bca76baf1cabd9e5c26f88efa18a0c3b1746bdc82d9 lastnum=695359 lasthash=0x87930ca3a81cfc2de1ac376d198c6f1a2652931118d61d12626ff5ee12395b06
DEBUG[08-15|00:37:16.342] 142:Data fetching completed              type=bodies
DEBUG[08-15|00:37:16.342] 142:Block body download terminated       err=nil
TRACE[08-15|00:37:16.343] Requiring new ethash cache               epoch=23
TRACE[08-15|00:37:16.343] Requiring new future ethash cache        epoch=24
DEBUG[08-15|00:37:16.343] 292:cache/generate                       dir=/opt/moacpool/.moac/moac/ethash limit=3 test=false
DEBUG[08-15|00:37:16.343] 291:cache/generate                       dir=/opt/moacpool/.moac/moac/ethash limit=3 test=false
DEBUG[08-15|00:37:16.343] Loaded old ethash cache from disk        epoch=23
DEBUG[08-15|00:37:16.343] 294:cache/generate                       dir=/opt/moacpool/.moac/moac/ethash limit=3 test=false
DEBUG[08-15|00:37:16.343] Loaded old ethash cache from disk        epoch=24
DEBUG[08-15|00:37:16.351] 145:[core/state_processor.go->Process] 
DEBUG[08-15|00:37:16.352] 145:[params/config.go->IsPangu] PanguBlock:0 num:695358 flag:true 
DEBUG[08-15|00:37:16.352] 145:[params/config.go->IsNuwa] NuwaBlock:647200 num:695358 
DEBUG[08-15|00:37:16.353] 145:[core/state_transition.go->ApplyMessage] msgHash 0x981befbf6de1706fbee4517264e99768ea78bedba0d35163981ccaaa01941813 
DEBUG[08-15|00:37:16.353] 145:[core/state_transition.go->TransitionDb in] 
DEBUG[08-15|00:37:16.353] 145:[params/config.go->IsPangu] PanguBlock:0 num:695358 flag:true 
DEBUG[08-15|00:37:16.353] 145:[core/vm/evm.go->Call] caller=0x0000000000000000000000000000000000000064 addr=0x0000000000000000000000000000000000000065 input=c1c0e9c4 code=7161 &evm.StateDB=0xc433d20080 
DEBUG[08-15|00:37:16.353] 145:[core/vm/evm.go->run] contract addr 0x0000000000000000000000000000000000000065 msgHash 0x981befbf6de1706fbee4517264e99768ea78bedba0d35163981ccaaa01941813 
DEBUG[08-15|00:37:16.353] 145:RunPrecompiledContract 
DEBUG[08-15|00:37:16.353] 145:RunPrecompiledContract contract.UseGas(gas) 
DEBUG[08-15|00:37:16.354] 145:input c1c0e9c4 
DEBUG[08-15|00:37:16.354] 145:Call returning ret [] leftOverGas 0 err <nil> 
DEBUG[08-15|00:37:16.354] 145:[core/types/transaction_signing.go->PanguSigner.Sender:99, ps 99
`

**Comment by Serpent6877** [comment]
Tested on a VM on my home network (Ubuntu 16.04) as well as a third network. Same peers always and limit of 2:

`
> admin.peers
[{
    caps: ["mc/62", "mc/63"],
    id: "3d8ba7cef2dcc8e25bd508e6a42d7b36a957afe8dc5cd9603ffd0857aae68b2768a06de6054816edec407a4579b15b5c7494e9c7e8323b015d6e9d518576e9eb",
    name: "Moac/v1.0.0-stable-5546a085/windows-amd64/go1.10.1",
    network: {
      localAddress: "192.168.1.254:38700",
      remoteAddress: "18.233.50.84:30333"
    },
    protocols: {
      mc: {
        difficulty: 13182641330555714000,
        head: "0xfc01a6a978a22c94fc8a998cbe91121a38976021ecffa1d9eefdc9a6faf8d66b",
        version: 63
      }
    }
}, {
    caps: ["mc/62", "mc/63"],
    id: "6f29307c8715502c11791704759d88910e091f5d4a6daf509fc9d0d8653967fd2cda76c94731e2db6654ff889a684a55f9a6bc6f0b3144282eb2c3e7cbccb4b1",
    name: "Moac/v1.0.0-stable-5546a085/linux-amd64/go1.10.1",
    network: {
      localAddress: "192.168.1.254:39628",
      remoteAddress: "18.211.187.153:30333"
    },
    protocols: {
      mc: {
        difficulty: 13182693834327366000,
        head: "0xc0758e819cff5c66bf0bb59e886accf51acc70033c36750b2f54caec968ac152",
        version: 63
      }
    }
}]
`

**Comment by mdranger** [comment]
Please check your port TCP/IP inbound/outbound control rules of your VM and data center computer. We found AWS/GOOGLE CLOUD need to open 30333 port in inbound/outbound. Otherwise it may connect to some internal IPs but not external machines.

**Comment by Serpent6877** [comment]
I made no changes and brought my node up today. It now is showing peers on all three of my servers. Not sure what has changed. Could it be a bad boot node? I tested many times with no firewall and even used the default port as shown above:

moac --fast --cache=2048 --rpc --rpcaddr 127.0.0.1 --rpcport 18011 --unlock 0x711635d6c48d9301e865548851605ddca2b9ca9e --password passfile

**Comment by Serpent6877** [comment]
No they are not. And these are not cloud servers. Two are dedicated in separate data centers and the other was a VM on my home PC on cable.

**Comment by mdranger** [comment]
Please use the most recent releases.
