### ISSUE TITLE
Subchain logic?

### ISSUE THREAD

**Issue by abc114437** [MOACChain/moac-core#47]
![1](https://user-images.githubusercontent.com/22112598/44509666-ec2e1f00-a6e4-11e8-918e-49e6369fae1e.png)
![2](https://user-images.githubusercontent.com/22112598/44509674-f2bc9680-a6e4-11e8-9f3c-47e121ae806c.png)
![3](https://user-images.githubusercontent.com/22112598/44509689-f819e100-a6e4-11e8-910c-54344dd8536f.png)
After the completion of the subchain,I send logical contracts.But sub chains do not carry out transactions,as shown in the picture.
Then,I use the RPC request in video mode to return error code 415(Monitor has been set up).

**Comment by abc114437** [comment]
And,the Protocol and Vnode I use are
![4](https://user-images.githubusercontent.com/22112598/44510220-a3776580-a6e6-11e8-97ce-858be48854ee.png)

**Comment by mdranger** [comment]
The via should be the vnode beneficial address. If you are using the vnode from the Vnode Protocol Pool in https://nodes101.moac.io, it is the Vnode Protocol Base Address displayed.
