### ISSUE TITLE
subchain scs and filestorm, are they ready for MAINNET?

### ISSUE THREAD

**Issue by lospringliu** [MOACChain/moac-core#48]
I read through the wiki and did not find out how to make my vnode capable to register scs.
And the slack community in website moan.io does not accept new user.

Is subchain and filestorm really ready?

**Comment by mdranger** [comment]
Please check the most recent documents on 
https://moacdocs-chn.readthedocs.io/zh_CN/latest
or 
https://moac-docs.readthedocs.io/en/latest/
