### ISSUE TITLE
Does the MOAC Block Explorer crash?

### ISSUE THREAD

**Issue by foreso-GitHub** [MOACChain/moac-core#5]
![moac explorer crash 1](https://user-images.githubusercontent.com/31951179/38532580-14f739fa-3ca8-11e8-806d-a0976d50e4a8.png)

**Comment by mdranger** [comment]
We are testing a new server and will replacing the old one when it is ready.
You can try this link
http://47.75.144.55:8000/

**Comment by foreso-GitHub** [comment]
Both 2 links are okay now, thanks!

BTW, are your team in LA?

**Comment by mdranger** [comment]
Great, our office is in Palo Alto.
