### ISSUE TITLE
CPU load 100% and can't reduce by para

### ISSUE THREAD

**Issue by wanpixiaozi** [MOACChain/moac-core#51]
I have used nuwa1.0.2 on Win7, the CPU load is 100% during mining.
I used '--minerthreads 1' para but no func at all, CPU load is still 100%

**Comment by mdranger** [comment]
How many CPUs do you have? --minerthreads 1 should only use one CPU.

**Comment by wanpixiaozi** [comment]
![cpuload](https://user-images.githubusercontent.com/39391886/45789826-515d3c00-bcb4-11e8-8638-3b8baaf596cf.PNG)
![moacrun](https://user-images.githubusercontent.com/39391886/45789827-51f5d280-bcb4-11e8-9a65-fcbf654df4f7.PNG)
![thread](https://user-images.githubusercontent.com/39391886/45789828-51f5d280-bcb4-11e8-8e4e-d92b47435910.PNG)
My CPU is i3-2370M, i found before miner.start, moac used 11 threads, after miner.start, moac used 15 threads

**Comment by mdranger** [comment]
i3-2370M is a low level CPU for MOAC VNODE mining, it only has 2 cores and 3M cache. We recommended i7 and up if you want to try CPU mining. However, GPU mining is recommended.

**Comment by mdranger** [comment]
The mining uses lots of computation power and that's why we suggest using i7 and similar CPU to do CPU mining.

**Comment by wanpixiaozi** [comment]
I found run `miner.start(1)` at moac console can run 1 mining thread, this can solve this problem
