### ISSUE TITLE
Other applications

### ISSUE THREAD

**Issue by limxuanhui** [MOACChain/moac-core#52]
Hi,

What are some of the other possible applications of the MOAC software apart from mining? For example, can the program take in data sets and output the transaction speeds of MOAC in handling those data?

Thank you.

**Comment by mdranger** [comment]
MOAC is a blockchain platform that supports smart contract written in Solidity. You can use smart contracts to do various applications. You can check the documents for solidity 
https://solidity.readthedocs.io/en/v0.4.25/
and some example projects:
http://erc721.org/
https://cryptozombies.io/
