### ISSUE TITLE
127.0.0.1:6060 - what is it?

### ISSUE THREAD

**Issue by temandroid** [MOACChain/moac-core#61]
Node trying to bind port 6060 but it already used by another daemon and I need to change it, but can't find how...
`Start MOAC nuwa 1.0.9-rc ...`
`2019/07/30 10:21:46 listen tcp 127.0.0.1:6060: bind: address already in use`
By "help" I found --pprofport option, but --pprof is disabled.
Can u tell me how I can change port 6060 to another one?

**Comment by mdranger** [comment]
This is a bug in the nuwa 1.0.9-rc that let the pprof port open, please use the updated stable version.

**Comment by temandroid** [comment]
It was downloaded from release page and have no RC mark, but now same link with another file, all works good, thx.
