### ISSUE TITLE
Cannot deploy smart contract combined by solidity 0.5 (or above) successfully, if operate address type in its constructor

### ISSUE THREAD

**Issue by foreso-GitHub** [MOACChain/moac-core#63]
Cannot deploy smart contract combined by solidity 0.5 (or above) successfully, if operate address type in its constructor.

1. A simple contract.

pragma solidity ^0.5.5;

contract Ownable {
  address private owner;

  constructor() public {
    owner = msg.sender;
    //owner = address(0);
    //owner = 0xdCad3a6d3569DF655070DEd06cb7A1b2Ccd1D3AF;
  }
}

2. If it is compiled in solidity 0.5 (or above), it will fail to deploy on moac.  All gas is consumed.  (9000000 gas).

3. If deploy it on eth, it works.

4. If compile it in solidity 0.4.24 and then deploy it on moac, it works.

**Comment by mdranger** [comment]
MOAC VNODE client supports  Solidity 0.8 compiler since Fuxi v2.0.1
