### ISSUE TITLE
moac node - error

### ISSUE THREAD

**Issue by slavserver** [MOACChain/moac-core#68]
every 3-4 days the node is used to make a resync from 1 block ... the node constantly goes into error...
I am using the latest and previous version, the problem is not fixed

**Comment by Serpent6877** [comment]
Are you seeing this?  #69

**Comment by wangyifan** [comment]
@slavserver It looks like your node is in a weird state right now. If #69 does not help, you can also just delete the data directory and re-sync. If you fast-sync, it should just take a few hours, given a good internet connection.

**Comment by slavserver** [comment]
4 times full resynchronization? ))))))))))))))))) the problem is not fixed ... please fix the assembly of the node

**Comment by wangyifan** [comment]
@slavserver can you paste the error log entries here? That would help to diagnose the problem.

**Comment by slavserver** [comment]
Rewinding blockchain                     target=1
every 3-4 days

**Comment by slavserver** [comment]
check it please

**Comment by slavserver** [comment]
at the moment I have deleted the pool and your node .... tired of doing a full resync .... fix the error

**Comment by mdranger** [comment]
Please check the release v2.0.4 and let us know if it works.
Thanks
