### ISSUE TITLE
transaction status problem

### ISSUE THREAD

**Issue by heipacker** [MOACChain/moac-core#7]
version:
Moac/v0.8.1-develop-0302101e/linux-amd64/go1.10

transaction hash:
0x239888fa24d0a9605ed3ead29e4e54fc2c96cb89fd19debe93add5123f5332d8

problem:
It was submitted for a long time, but still in pending status

**Comment by mdranger** [comment]
What's the gasPrice?

**Comment by mdranger** [comment]
The minimal gas price to accept for mining a transactions is 18 GSha/Xiao in MOAC system. If the gasPrice is lower than this value, the TX will be in pending until you raise the gasPrice.
